<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1MEML7A" failures="1" tests="1" name="ErrorMethod" time="88.851" errors="0" timestamp="2024-04-10T16:10:37 IST">
  <testcase classname="Ecommerce.ErrorCheck" name="ErrorCheckd" time="70.855">
    <failure type="java.lang.IllegalArgumentException" message="Error">
      <![CDATA[java.lang.IllegalArgumentException: Error
at dev.failsafe.internal.util.Assert.isTrue(Assert.java:29)
at Ecommerce.ErrorCheck.ErrorCheckd(ErrorCheck.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ErrorCheckd -->
</testsuite> <!-- ErrorMethod -->
